<?php
return array(
  'path' => str_replace('\\', '/', dirname(__FILE__)),
  'name' => 'Jivoo',
  'version' => '0.15-dev-3',
  'website' => 'http://jivoo.org',
  'defaultLanguage' => 'en',
  'minPhpVersion' => '5.2.0',
  'sessionPrefix' => 'jivoo_',
  'extensions' => array('Jquery', 'JqueryHotkeys', 'JqueryUi', 'Tinymce', 'BasicWidgets'),
  'modules' => array(
    'Jivoo/Core',
    'Jivoo/Routing',
    'Jivoo/Assets',
    'Jivoo/Templates',
    'Jivoo/Controllers',
    'Jivoo/Setup',
    'Jivoo/Models', 
    'Jivoo/Editors',
    'Jivoo/Shadow',
    'Jivoo/Database',
    'Jivoo/Authentication',
    'Jivoo/Helpers',
    'Jivoo/Administration',
    'Jivoo/Theme',
    'Jivoo/Extensions',
    'Jivoo/Widgets',
    'PeanutCMS/Backend',
    'PeanutCMS/Pages',
    'PeanutCMS/Blog',
  ),
);
