<?php
return array(
  'path' => str_replace('\\', '/', dirname(__FILE__)),
  'name' => 'PeanutCMS',
  'version' => '0.14.1',
  'website' => 'http://peanutcms.apakoh.dk',
  'defaultLanguage' => 'en',
  'minPhpVersion' => '5.2.0',
  'sessionPrefix' => 'peanut_',
  'extensions' => array('Jquery', 'JqueryHotkeys', 'JqueryUi', 'Tinymce'),
  'modules' => array(
    'Core',
    'Core/Routing',
    'Core/Assets',
    'Core/Templates',
    'Core/Controllers',
    'Core/Setup',
    'Core/Models', 
    'Core/Editors',
    'Core/Shadow',
    'Core/Database',
    'Core/Authentication',
    'Core/Helpers',
    'Core/Toolkit',
    'PeanutCMS',
    'PeanutCMS/Backend',
    'PeanutCMS/Widgets',
    'PeanutCMS/Links',
    'PeanutCMS/Pages',
    'PeanutCMS/Posts',
    'PeanutCMS/Theme',
    'PeanutCMS/Extensions',
  ),
);
