<?php
return array(
  Route::root('Posts::index'),
  Route::error('App::notFound'),
  Route::match('posts', 'Posts::index'),
  Route::match('archive', 'Posts::archive'),
  Route::match('tags', 'Posts::tagIndex'),
  Route::match('tags/*', 'Posts::viewTag'),
  Route::match('posts.rss', 'Posts::feed'),
  Route::auto('Admin'),
  Route::auto('Admin::Posts'),
  Route::auto('Admin::Tags'),
  Route::auto('Admin::Pages'),
  Route::auto('Admin::Comments'),
  Route::auto('Admin::Users'),
  Route::auto('Admin::Extensions'),
  Route::auto('Admin::Configuration'),
  Route::auto('Admin::Media'),
  Route::auto('Admin::Menus'),
  Route::auto('Admin::Themes'),
  Route::auto('Admin::Widgets'),
);
